### ISSUE TITLE
Missing /usr/bin/dot using plantuml

### ISSUE THREAD

**Issue by LorenzoLuconi** [rochdev/docker-alpine-asciidoctor#6]
I wrote a simple AsciiDoc document containing a plantuml diagram, but when I try to render it an exception is thrown:

```
$ docker run -it --rm -v ${PWD}:/documents rochdev/alpine-asciidoctor asciidoctor -r asciidoctor-diagram documentation.adoc
java.io.IOException: Cannot run program "/usr/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:158)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:118)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:74)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
```

It looks like something is missing, maybe graphviz is not fully installed. It works fine with ditaa diagram.

Thank you.
Lorenzo

**Comment by rochdev** [comment]
Are you allowed to share the adoc file? Otherwise can you share the failing snippet?

**Comment by LorenzoLuconi** [comment]
```
docker run -it --rm -v ${PWD}:/documents rochdev/alpine-asciidoctor asciidoctor -r asciidoctor-diagram test.txt
```
[test.txt](https://github.com/rochdev/docker-alpine-asciidoctor/files/1380139/test.txt)
